<template>
    <v-container class="my-5">
      <v-row justify="center">
        <v-col cols="12" md="8">
          <v-card class="elevation-2">
            <v-card-title class="headline mb-0">Privacy Policy</v-card-title>
            <v-divider class="mt-3"></v-divider>
            <v-card-text>
              <p class="mb-3">Our website uses Google Analytics, a web analytics service provided by Google. Google Analytics uses cookies, which are small text files that are placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.</p>
              <p class="mb-3">Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google.</p>
              <p class="mb-3">By using our website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>
              <p class="mb-3">We also use cookies on our website. Cookies are small text files that are placed on your computer by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owners of the site. We use cookies to improve your experience on our website and to understand how you interact with our content.</p>
              <p class="mb-0">By using our website, you consent to the use of cookies in accordance with our Privacy Policy. You may choose to disable cookies in your web browser settings, but please note that this may affect your ability to use certain features of our website.</p>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </template>
  